
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle custom domain redirects for your plan
[[redirects]]
  from = "https://site-:id.netlify.app/*"
  to = "https://site-:id.netlify.app/:splat"
  status = 200
  force = false

# Handle SPA routing for all domains
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API routes and prevent them from being redirected
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle site routes for live websites
[[redirects]]
  from = "/site/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/view/*"
  to = "/index.html"
  status = 200

# Handle e-commerce routes
[[redirects]]
  from = "/cart"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/product/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/checkout/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for performance
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"

# Forms handling for contact forms
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
