// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmzpekwpzacjymymwtak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptenBla3dwemFjanlteW13dGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDAyMjYsImV4cCI6MjA2MjQ3NjIyNn0.hTozleYwfybgNod9ep1Yt_SBtB2ztA574bDxqpaLzNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);